---
title: "OA Dashboard"
author: "Tom Saunders"
output:
  html_document:
    css: "style.css"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'index.html')) })
---
```{r, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(fig.align="center")
library(tidyverse)
```

This dashboard reads in data extracted from the Open Alex API via [this query](open-alex-query.Rmd), calculates a variety of metrics, and visualises the data in a series of plots to show trends at a national and institution-specific level since 2010. Plots are shown on the page and saved into the `/fig` directory.

```{r}
# Get most current full year

prev_year <- as.numeric(format(Sys.Date(), "%Y"))-1

# Read in data generated by Open Alex query

oa_nz <- read.csv("data/oa_nz_2023.csv")

# Calculate overall access status proportions for each year

oa_nz_trend <- oa_nz |> 
  group_by(year,oa_type) |> 
  summarise(
    value = sum(value),
  ) |> 
  group_by(year) |> 
  summarise(
    year = year,
    oa_type = oa_type,
    value = value,
    pc = value / sum(value) * 100,
  ) |> 
  mutate(
    open = case_when(oa_type != "closed" ~ "open", .default = oa_type),
  ) |> 
  group_by(year, open) |> 
  summarise(
    pc = sum(pc),
  ) |> 
  filter(open == "open")
```

```{r}
# Plot by open type

oa_nz_trend_title <- paste0("Open Access Publication Output by New Zealand Universities, 2010-", prev_year)

ggplot(oa_nz_trend, aes(x = year, y = pc)) +
  geom_line(size = 1, colour = "#4DAF4A", show.legend = FALSE) +
  theme_classic() +
  xlab("") +
  ylab("%") +
  ylim(0, 80) +
  scale_x_continuous(n.breaks = prev_year-2010) +
  ggtitle(oa_nz_trend_title)

ggsave("fig/1-nz-oa-output.png")
```

```{r}
# Plot by access type

oa_nz_types_title <- (paste0("Access Status for NZ University Publications, 2010-", prev_year))

oa_nz_types <- oa_nz |> 
  group_by(year,oa_type) |> 
  summarise(
    value = sum(value),
  ) |> 
  group_by(year) |> 
  summarise(
    year = year,
    oa_type = oa_type,
    value = value,
    pc = value / sum(value) * 100,
  )
  
ggplot(oa_nz_types, aes(x = year, y = pc, colour = oa_type)) +
  geom_line(size = 1) +
  theme_classic() +
  scale_colour_manual(name = "OA Type", 
                     values = c("bronze" = "#A65628",
                                "hybrid" = "#377EB8",
                                "gold" = "#FFFF33",
                                "green" = "#4DAF4A",
                                "closed" = "#E41A1C")) +
  xlab("") +
  ylab("%") +
  ylim(0, 80) +
  scale_x_continuous(n.breaks = prev_year-2010) +
  ggtitle(oa_nz_types_title)

ggsave("fig/2-access-status-all.png")
```

```{r}
oa_nz_unis <- oa_nz |> 
  filter(year == 2023) 

oa_nz_unis$oa_type <- factor(oa_nz_unis$oa_type, 
                            levels = c("bronze","green", "hybrid", "gold", "closed"))

oa_nz_unis_title <- (paste0("OA Type by Institution, ", prev_year))
  
ggplot(oa_nz_unis, aes(x = institution, y = pc, fill = oa_type)) +
  geom_bar(position="dodge", stat="identity") +
  scale_fill_manual( name = "OA Type", 
                     values = c("bronze" = "#A65628",
                                "hybrid" = "#377EB8",
                                "gold" = "#FFFF33",
                                "green" = "#4DAF4A",
                                "closed" = "#E41A1C")) +
  coord_flip() +
  theme_classic() +
  xlab("") +
  ylab("%") +
  ggtitle(oa_nz_unis_title)

ggsave("fig/3-type-institution.png")
```

```{r, fig.width=7, fig.height=25}
plot_titles_all <- paste0("Access Status for ", unique(oa_nz$institution), ", 2010-", prev_year)

plot_function <- function(oa_nz) {
  p <- ggplot(oa_nz, aes(x = year, y = pc, colour = oa_type))
  p <- p + geom_line(size = 1) +
    scale_colour_manual(name = "OA Type", 
                        values = c("bronze" = "#A65628",
                                   "hybrid" = "#377EB8",
                                   "gold" = "#FFFF33",
                                   "green" = "#4DAF4A",
                                   "closed" = "#E41A1C")) +
    theme_classic() +
    xlab("") +
    ylab("%") +
    ylim(0, 80) +
    scale_x_continuous(n.breaks = prev_year-2010)
  return(p)
}

plot_list <- oa_nz |> 
  group_split(institution) |> 
  map(~ plot_function(.x))

plot_list <- lapply(seq_along(plot_list), function(i) { 
  plot_list[[i]] + ggtitle(plot_titles_all[i])
})

wrapped_plot <- patchwork::wrap_plots(plot_list, ncol = 1)

nb_plots <- length(plot_list)
baseheight <- grDevices::dev.size(units = "px")[1]
ggsave("fig/4-trend-all.png",
       wrapped_plot,
       height = nb_plots * baseheight,
       units = "px",
       limitsize = FALSE)

wrapped_plot
```

