---
title: "Open Alex Query"
author: "Tom Saunders"
output: html_document
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'index.html')) })
---
This script queries the Open Alex API to retrieve the publication status for articles, books, and book chapters with an author affiliated with a NZ university. It determines the current year, retrieves data for the previous year, and automatically uses the appropriate year in the title of the plot.

```{r, message=FALSE}
library(jsonlite)
library(tibble)
library(stringr)
library(dplyr)
library(ggplot2)
```

```{r, warning=FALSE}
# Get institutions and rors

institutions <- data.frame(institution  = c("University of Auckland",
                                            "Auckland University of Technology",
                                            "University of Waikato",
                                            "Massey University",
                                            "Victoria University of Wellington",
                                            "University of Canterbury",
                                            "Lincoln University",
                                            "University of Otago"),
                      ror = c("https://ror.org/03b94tp07",
                              "https://ror.org/01zvqw119",
                              "https://ror.org/013fsnh78",
                              "https://ror.org/052czxv31",
                              "https://ror.org/0040r6f76",
                              "https://ror.org/03y7q9t39",
                              "https://ror.org/04ps1r162",
                              "https://ror.org/01jmxt844")
)

# Define filters

prev_year <- as.numeric(format(Sys.Date(), "%Y"))-1

parameters <- paste(c(
  "is_paratext:false",
  "type:article|book|book-chapter",
  (paste0("publication_year:", prev_year)),
  "is_retracted:false"), 
  collapse = ",")

# Create URLs

institutions$request <- paste0("https://api.openalex.org/works?filter=institutions.ror:", 
                   institutions$ror, 
                   ",", 
                   parameters,
                   "&group_by=oa_status")

raw_json <- NULL

for (i in 1:length(institutions$request)) {
  raw_json[[i]] <- (read_json(institutions$request[[i]], simplifyVector = TRUE))
}

raw_data <- enframe(unlist(raw_json))
raw_data$value <- as.numeric(raw_data$value)

oa_status <- raw_data |> 
  filter(str_detect(raw_data$name, "group_by.count")) |> 
  mutate(
    institution = case_when(row_number() %in% 1:5 ~ institutions$institution[1],
                            row_number() %in% 6:10 ~ institutions$institution[2],
                            row_number() %in% 11:15 ~ institutions$institution[3],
                            row_number() %in% 16:20 ~ institutions$institution[4],
                            row_number() %in% 21:25 ~ institutions$institution[5],
                            row_number() %in% 26:30 ~ institutions$institution[6],
                            row_number() %in% 31:35 ~ institutions$institution[7],
                            row_number() %in% 36:40 ~ institutions$institution[8]),
    oa_type = rep(c("closed", 
                    "gold", 
                    "hybrid", 
                    "green", 
                    "bronze"),
                  8),
  ) |> 
  group_by(institution) |> 
  mutate(
    pc = (value / sum(value) * 100),
  ) |> 
  select(institution, oa_type, value, pc)

write.csv(oa_status, "data/oa_status.csv", row.names = FALSE)

oa_status$oa_type <- factor(oa_status$oa_type, 
                            levels = c("bronze","green", "hybrid", "gold", "closed"))

title <- (paste("OA Status for", prev_year, "Publications"))

ggplot(oa_status, aes(x = institution, y = pc, fill = oa_type)) +
  geom_bar(position="dodge", stat="identity") +
  scale_fill_manual( name = "OA Type", 
                     values = c("bronze" = "#ffdfba",
                                "hybrid" = "#bae1ff",
                                "gold" = "#ffffba",
                                "green" = "#baffc9",
                                "closed" = "#ffb3ba")) +
  coord_flip() +
  theme_classic() +
  xlab("") +
  ylab("%") +
  ggtitle(title)
```

