---
title: |
  |
  |
  |
  | University of Auckland 
  | Open Access Publication Analysis: 
  | 2015-2024
  |
  |
  |
subtitle: |
  | Prepared for 
  | Te Tumu Herenga | Libraries and Learning Services
  |
  |
  |
  |
  |
  |
  |
  |
  |
author: "Tom Saunders"
date: 2025-04-01
date-format: long
output-file: "uoa-report.pdf"
format:
  typst:
    margin:
      x: 2cm
      y: 2cm
    fig-width: 8
    # fig-height: 
# bibliography: 
# bibliographystyle:   
execute:
  echo: false
fig-align: center
---

```{r}
#| message: false
library(dplyr)
library(ggplot2)
library(scales)
library(tidyr)
library(ggthemes)
library(gt)

uoa_data <- read.csv("uoa-data.csv")

plot_colours <- c("bronze" = "#A65628",
                  "hybrid" = "#377EB8",
                  "gold" = "#FFFF33",
                 "diamond" = "lightgrey",
                 "green" = "#4DAF4A",
                 "closed" = "#E41A1C")

plot_theme <- function(base_size=14, base_family="sans") {
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5, margin = margin(0,0,20,0)),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line.x = element_line(colour="black"),
               axis.line.y = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "right",
               legend.direction = "vertical",
               legend.box = "vertical",
               legend.key.size= unit(0.5, "cm"),
               #legend.margin = unit(0, "cm"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
       ))
      
}
```

{{< pagebreak >}}

General OA publication stats, comparisons with other unis

```{r}
#| message: false

# Publication output over time by oa status

uoa_data$oa_status <- factor(uoa_data$oa_status, levels = c("closed",
                                                              "bronze",
                                                              "hybrid",
                                                              "gold",
                                                              "green",
                                                              "diamond"))

uoa_data |> 
  group_by(publication_year, oa_status) |> 
  summarise(
    n = n(),
  ) |> 
  mutate(
    percent = n / sum(n),
  ) |> 
  ggplot(aes(x = publication_year, y = percent, fill = oa_status)) +
  geom_area() +
  scale_fill_manual(name = "Access Type",
                      values = plot_colours) +
  plot_theme() +
  xlab("") +
  ylab("Proportion (%)") +
  scale_y_continuous(labels = label_percent()) +
  scale_x_continuous(breaks = unique(uoa_data$publication_year))
  
  
```


```{r}
# Number of different items in each type

uoa_data |> 
  count(type) |> 
  mutate(freq = n / sum(n)) |> 
  arrange(desc(n)) |> 
  gt() |> 
  cols_label(type = "Item Type",
             n = "Count",
             freq = "Proportion") |> 
  fmt_percent(columns = freq)
  
```

```{r}
# Number of citations each year (table)

uoa_data |> 
  group_by(publication_year) |> 
  summarise(
    Works = format(n(), big.mark = ","),
    Citations = format(sum(cited_by_count), big.mark = ","),
    Min = min(cited_by_count),
    Max = format(max(cited_by_count), big.mark = ","),
    Median = median(cited_by_count),
    Average = round(mean(cited_by_count), digits = 1)
  ) |>
  gt() |> 
  cols_label(publication_year = "Year")
```

```{r}
# Spread of citations

uoa_data |>
  ggplot(aes(x = cited_by_count)) +
  stat_density(aes(y = after_stat(count)), color = "black", fill = "#f3f2f2") +
  scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5, 10, 100, 1000), trans = "log1p", expand = c(0, 0)) +
  plot_theme() +
  xlab("Citations (log1p)") +
  ylab("Works") +
  scale_y_continuous(labels = comma)
```

```{r}
# Number of citations each year (plot)

uoa_data |> 
  group_by(publication_year) |> 
  summarise(
    total = sum(cited_by_count),
    median = median(cited_by_count),
    average = mean(cited_by_count)
  ) |> 
  arrange(desc(publication_year)) |> 
  ggplot(aes(x = publication_year, y = total)) +
  geom_col(fill = "#377EB8") +
  plot_theme() +
  scale_x_continuous(breaks = unique(uoa_data$publication_year)) +
  ylab("Citations") +
  xlab("")

```


```{r}
#| message: false
# Overall, mean & median citations, OA vs closed

uoa_data |> 
  group_by(is_oa) |> 
  summarise(
    avg_citations = round(mean(cited_by_count)),
    med_citations = median(cited_by_count)
  ) |> 
  gt() |> 
  cols_label(is_oa = "",
             avg_citations = "Mean Citations",
             med_citations = "Median Citations") |> 
  sub_values(values = "FALSE", replacement = "Closed") |>
  sub_values(values = "TRUE", replacement = "Open")
```

```{r}
#| message: false

# Each year, median citation OA vs closed

uoa_data$is_oa <- factor(uoa_data$is_oa, levels = c(TRUE, FALSE))

uoa_data |> 
  group_by(publication_year, is_oa) |> 
  summarise(
    med_citations = median(cited_by_count)
  ) |> 
  ggplot(aes(x = publication_year, y = med_citations, fill = is_oa)) +
  geom_bar(position="dodge", stat="identity") +
  plot_theme() +
  scale_x_continuous(breaks = unique(uoa_data$publication_year)) +
  ylab("Median Citations") +
  xlab("") +
  scale_fill_manual(name = "Access Type",
                    labels = c("Open", "Closed"),
                    values = c("#4DAF4A", "#E41A1C"))
```

```{r}
# Difference in citations each year between open vs closed

cit_diff_oa <-
uoa_data |> 
  group_by(publication_year, is_oa) |> 
  summarise(
    med_citations = median(cited_by_count),
  ) |>
  pivot_wider(names_from = is_oa, values_from = med_citations) |> 
  mutate(
    difference = `FALSE` / `TRUE`,
  )

cat("Each year, open access items enjoy median citation rates between", scales::percent(min(cit_diff_oa$difference, na.rm = TRUE)), "and",  scales::percent(max(cit_diff_oa$difference, na.rm = TRUE)), "higher than closed items.")
```


```{r}
#| message: false

# Overall, median citations for each type of OA vs closed

uoa_data |> 
  group_by(oa_status) |> 
  summarise(
    med_citations = median(cited_by_count)
  ) |> 
  ggplot(aes(x = reorder(oa_status, -med_citations), y = med_citations)) +
  geom_col(fill = "#377EB8") +
  plot_theme() +
  ylab("Median Citations") +
  xlab("")
  
```

```{r}
# Each year, median citations for each type of OA vs closed

uoa_data |> 
  filter(publication_year != 2024) |> 
  group_by(publication_year, oa_status) |> 
  summarise(
    med_citations = median(cited_by_count),
  ) |> 
  ggplot(aes(x = publication_year, y = med_citations, fill = oa_status)) +
  geom_bar(position="fill", stat="identity") +
  plot_theme() +
  scale_x_continuous(breaks = unique(uoa_data$publication_year)) +
  ylab("Median Citations") +
  xlab("") +
  scale_fill_manual(name = "Access Type",
                      values = plot_colours) +
  scale_y_continuous(labels = label_percent())
  


```

```{r}
uoa_data |>
  drop_na(field) |> 
  group_by(field, is_oa) |> 
  tally() |> 
  mutate(
    pc = n / sum(n)
    ) |>
  filter(is_oa == TRUE) |>
  ggplot(aes(x = reorder(field, pc), y = pc)) +
  geom_bar(position="dodge", stat="identity", fill = "#4DAF4A") +
  coord_flip() +
  plot_theme() +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = label_percent(),
                     limits = c(0, 0.8))

```

